# Generated by Django 6.0.1 on 2026-01-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exhibit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("domain", models.CharField(max_length=100)),
                ("deployment_context", models.TextField()),
                ("intended_use", models.TextField()),
                ("system_type", models.CharField(max_length=100)),
                ("inputs_and_assumptions", models.TextField()),
                ("outputs_presented", models.TextField()),
                ("failure_description", models.TextField()),
                ("detection_method", models.TextField()),
                ("affected_parties", models.TextField()),
                ("contributing_factors", models.TextField()),
                ("lessons_learned", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("correct_answer", models.CharField(max_length=200)),
                ("explanation", models.TextField()),
                (
                    "exhibit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="exhibits.exhibit",
                    ),
                ),
            ],
        ),
    ]
