# Generated by Django 5.2.10 on 2026-01-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_answer_index',
            field=models.IntegerField(default=0, help_text='Index of the correct answer in options list'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of multiple choice options'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
