# Generated by Django 5.2.10 on 2026-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0002_remove_quiz_correct_answer_quiz_correct_answer_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to an image representing this exhibit', null=True),
        ),
    ]
