# Generated by Django 5.2.10 on 2026-01-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0003_exhibit_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='data_issues',
            field=models.TextField(blank=True, help_text='Data-related issues that contributed to the failure'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='organizational_factors',
            field=models.TextField(blank=True, help_text='Organizational and governance factors'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='supporting_artefacts',
            field=models.JSONField(blank=True, default=list, help_text='List of supporting artefact links'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='technical_choices',
            field=models.TextField(blank=True, help_text='Technical choices that contributed to the failure'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='timeline',
            field=models.TextField(blank=True, help_text='Timeline of failure and aftermath'),
        ),
    ]
