# Generated by Django 5.2.10 on 2026-01-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0004_exhibit_data_issues_exhibit_organizational_factors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='image_reference',
            field=models.CharField(blank=True, help_text='Reference/attribution for the image', max_length=200, null=True),
        ),
    ]
