# Generated by Django 5.2.10 on 2026-01-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0005_exhibit_image_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='image_url',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(blank=True, help_text='Image representing this exhibit', null=True, upload_to='exhibits/images/'),
        ),
    ]
