# Generated by Django 5.2.10 on 2026-02-22 15:20

from django.db import migrations, models


def migrate_access_levels(apps, schema_editor):
    """Convert old access levels (viewer, contributor, moderator) to 'user'."""
    UserProfile = apps.get_model("exhibits", "UserProfile")
    UserProfile.objects.exclude(access_level="admin").update(access_level="user")


def reverse_migrate_access_levels(apps, schema_editor):
    """Reverse: set non-admin to viewer."""
    UserProfile = apps.get_model("exhibits", "UserProfile")
    UserProfile.objects.exclude(access_level="admin").update(access_level="viewer")


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(migrate_access_levels, reverse_migrate_access_levels),
        migrations.AlterField(
            model_name='userprofile',
            name='access_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('curator', 'Curator'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
